option_settings:
  aws:elasticbeanstalk:environment:proxy:
    NginxServerConfig: /etc/nginx/conf.d/proxy.conf

files:
  "/etc/nginx/conf.d/proxy.conf":
    mode: "000755"
    owner: root
    group: root
    content: |
      location / {
        proxy_pass http://localhost:8081; # Assuming your Node.js app is running on port 8081
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
